=== caizefeng/BayesianOpt4dftu/BayesOpt4dftu/schemas/input_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "vasp_env": {
            "type": "object",
            "properties": {
                "vasp_run_command": {
                    "type": "string"
                },
                "out_file_name": {
                    "type": "string"
                },
                "vasp_pp_path": {
                    "type": "string"
                },
                "dry_run": {
                    "type": "boolean"
                },
                "dftu_only": {
                    "type": "boolean"
                },
                "get_optimal_band": {
                    "type": "boolean"
                }
            },
            "required": [
                "vasp_run_command",
                "vasp_pp_path"
            ],
            "additionalProperties": false
        },
        "bo": {
            "type": "object",
            "properties": {
                "resume_checkpoint": {
                    "type": "boolean"
                },
                "baseline": {
                    "type": "string",
                    "enum": [
                        "hse",
                        "gw"
                    ]
                },
                "which_u": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "enum": [
                            0,
                            1
                        ]
                    }
                },
                "br": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "minItems": 2,
                    "maxItems": 2
                },
                "kappa": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 10
                },
                "alpha_gap": {
                    "type": "number",
                    "minimum": 0
                },
                "alpha_band": {
                    "type": "number",
                    "minimum": 0
                },
                "alpha_mag": {
                    "type": "number",
                    "minimum": 0
                },
                "threshold": {
                    "type": "number",
                    "minimum": 0
                },
                "urange": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "elements": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "iteration": {
                    "type": "integer",
                    "minimum": 1
                },
                "report_optimum_interval": {
                    "type": "integer",
                    "minimum": 2
                }
            },
            "required": [
                "baseline",
                "which_u",
                "br",
                "kappa",
                "alpha_gap",
                "alpha_band",
                "alpha_mag",
                "threshold",
                "urange",
                "elements",
                "iteration"
            ],
            "additionalProperties": false
        },
        "structure_info": {
            "type": "object",
            "properties": {
                "lattice_param": {
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "cell": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "minItems": 3,
                        "maxItems": 3
                    },
                    "minItems": 3,
                    "maxItems": 3
                },
                "atoms": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "number"
                                },
                                "minItems": 3,
                                "maxItems": 3
                            },
                            {
                                "anyOf": [
                                    {
                                        "type": "array",
                                        "items": {
                                            "type": "number"
                                        },
                                        "minItems": 3,
                                        "maxItems": 3
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "type": "number"
                                        },
                                        "minItems": 1,
                                        "maxItems": 1
                                    }
                                ]
                            }
                        ],
                        "minItems": 3,
                        "maxItems": 3
                    }
                },
                "kgrid_hse": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "minItems": 3,
                    "maxItems": 3
                },
                "kgrid_pbe": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "minItems": 3,
                    "maxItems": 3
                },
                "num_kpts": {
                    "anyOf": [
                        {
                            "type": "integer",
                            "minimum": 1
                        },
                        {
                            "type": "string",
                            "enum": [
                                "auto"
                            ]
                        }
                    ]
                },
                "kpath": {
                    "type": "string",
                    "pattern": "^(.+?)(\\s+.+?)+$"
                }
            },
            "required": [
                "lattice_param",
                "cell",
                "atoms",
                "kgrid_pbe",
                "num_kpts"
            ],
            "additionalProperties": false
        },
        "general_flags": {
            "type": "object",
            "additionalProperties": true
        },
        "scf": {
            "type": "object",
            "additionalProperties": true
        },
        "band": {
            "type": "object",
            "additionalProperties": true
        },
        "pbe": {
            "type": "object",
            "properties": {
                "ldau": {
                    "const": true
                },
                "ldau_luj": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "properties": {
                            "L": {
                                "type": "integer"
                            },
                            "U": {
                                "type": "number"
                            },
                            "J": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "L",
                            "U",
                            "J"
                        ]
                    }
                }
            },
            "required": [
                "ldau",
                "ldau_luj"
            ],
            "additionalProperties": true
        },
        "hse": {
            "type": "object",
            "additionalProperties": true
        }
    },
    "required": [
        "vasp_env",
        "bo",
        "structure_info",
        "general_flags",
        "scf",
        "band",
        "pbe",
        "hse"
    ],
    "additionalProperties": false
}

=== caizefeng/BayesianOpt4dftu/examples/2d/input.json
{
    "vasp_env": {
        "vasp_run_command": "mpirun -np 54 /trace/home/zefengc/soft/vasp.5.4.4.optcell/bin/vasp_ncl",
        "out_file_name": "slurm-vasp.out",
        "vasp_pp_path": "/trace/home/zefengc/soft/Pseudopotentials/",
        "dry_run": false,
        "dftu_only": false,
        "get_optimal_band": true
    },
    "bo": {
        "resume_checkpoint": false,
        "baseline": "hse",
        "which_u": [
            1,
            1
        ],
        "br": [
            5,
            5
        ],
        "kappa": 5,
        "alpha_gap": 0.25,
        "alpha_band": 0.75,
        "alpha_mag": 0.0,
        "threshold": 0.0001,
        "urange": [
            -10.0,
            10.0
        ],
        "elements": [
            "In",
            "As"
        ],
        "iteration": 200,
        "report_optimum_interval": 10
    },
    "structure_info": {
        "lattice_param": 6.0584,
        "cell": [
            [
                0.0,
                0.5,
                0.5
            ],
            [
                0.5,
                0.0,
                0.5
            ],
            [
                0.5,
                0.5,
                0.0
            ]
        ],
        "atoms": [
            [
                "In",
                [
                    0,
                    0,
                    0
                ],
                [
                    0,
                    0,
                    1e-06
                ]
            ],
            [
                "As",
                [
                    0.75,
                    0.75,
                    0.75
                ],
                [
                    0,
                    0,
                    1e-06
                ]
            ]
        ],
        "kgrid_hse": [
            7,
            7,
            7
        ],
        "kgrid_pbe": [
            7,
            7,
            7
        ],
        "num_kpts": 50,
        "kpath": "G X W L G K"
    },
    "general_flags": {
        "encut": 400,
        "sigma": 0.05,
        "ediff": 1e-05,
        "prec": "N",
        "algo": "D",
        "lsorbit": true,
        "saxis": [
            0,
            0,
            1
        ],
        "nbands": 21,
        "kpar": 6,
        "ncore": 3,
        "bmix": 3,
        "amin": 0.01,
        "lorbit": 11,
        "lmaxmix": 4
    },
    "scf": {
        "icharg": 2,
        "istart": 0,
        "xc": "pbe"
    },
    "band": {
        "icharg": 11,
        "lcharg": false,
        "lwave": false
    },
    "pbe": {
        "xc": "pbe",
        "ldau": true,
        "ldau_luj": {
            "In": {
                "L": 1,
                "U": 0.0,
                "J": 0.0
            },
            "As": {
                "L": 1,
                "U": 0.0,
                "J": 0.0
            }
        }

    },
    "hse": {
        "istart": 0,
        "icharg": 2,
        "xc": "hse06",
        "aexx": 0.25,
        "time": 0.4,
        "ldiag": true,
        "precfock": "Fast"
    }
}
